### ISSUE TITLE
Profile Page - Editing Information

### ISSUE THREAD

**Issue by mfestger** [2GatherOrg/2Gather#29]
- [x] Edit First Name
- [x] Edit Last Name
- [x] Edit Email
- [x] Edit Phone Number
- [x] Edit Date of Birth
- [x] Edit Bio

**Comment by MontealegreLuis** [comment]
Hey guys, great job! When you close an issue, could you add another comment with a link to the pull requests that closes the issue you can add the number of the PR or PRs with `#` and the number.

For instance:

Closed by #42 and #48
